CREATE table students (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR(100),
    last_name VARCHAR(100),
    email VARCHAR,
    subject VARCHAR,
    dateOfEnter TIMESTAMP
)